all:
	cp -v mindtouch.dream.dll* ../bin; \
	cp -v mindtouch.core.dll* ../bin; \
	cp -v mindtouch.webrequest.exe* ../bin; \
	cp -v mindtouch.host.exe* ../bin; \
	cp -v log4net.dll ../bin; \
	cp -v SgmlReaderDll.dll ../bin; \
	cp -v MySql.Data.dll ../bin; \
	cp -v nunit/nunit.framework.dll ../bin;
clean:

