java ^
 -jar google-compiler-20100917.jar^
 --js ISC_Core.js^
 --js ISC_Foundation.js^
 --js ISC_Containers.js^
 --js ISC_Grids.js^
 --js ISC_Forms.js^
 --js ISC_DataBinding.js^
 --js ISC_Calendar.js^
 --js_output_file ISC.min.js