MCS=gmcs
MCS_FLAGS=/d:DEBUG -debug+

CLEANFILES=$(ASSEMBLY) $(ASSEMBLY).mdb

PREFIX=$(root_dir)/bin
build_prefix=$(PREFIX)

clean:
	@failcom='exit 1'; \
	if test -f "$(addprefix $(PREFIX)/,$(ASSEMBLY))"; then \
	  rm -f $(addprefix $(PREFIX)/,$(ASSEMBLY)); \
	fi
