<?php
// This file was automatically generated by the MindTouch installer.
// If you make manual changes, please keep track in case you need to
// recreate them later.
//
// See includes/DefaultSettings.php for all configurable settings
// and their default values, but don't forget to make changes in _this_
// file, not there.

$IP = dirname(__FILE__);
ini_set("include_path", ".;$IP;$IP\includes;$IP\languages");
require_once("includes/DefaultSettings.php");

$wgEmergencyContact = "wq@wmios.com";
$wgPasswordSender = "wq@wmios.com";

$wgDekiApiKey = "dX3UOi5ZWqf3Pixsj0TlvLZl4aZsvrIm";

$wgDBserver = "192.168.1.94";
$wgDBname = "Heran_mindtouch_test_2";
$wgDBadminuser = "wikiuser";
$wgDBadminpassword = "cvV1xjTWLhJpYHDN";
